name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        
    - name: Push Container to ACR
      working-directory: src
      run: |
        docker build . -t ${{ secrets.ACR_LOGIN_SERVER }}/places-api::${{ github.sha }}
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/places-api::${{ github.sha }}
